/*
Demo of C code generated by the scanner generator.

*/
#include <stdio.h>

#include "scanner.h"

void main() {
    char* test_text = "67432 2323  bla   mo";

    lexer_t* lex = lexer_new();

    printf("Scanning: %s\n", test_text);

    while (test_text[lex->index] != 0) {
        int c = test_text[lex->index++];
        lexer_add(lex, c);
        if (lex->state == 0)
        {
            lex->index = lex->tok_end;
            printf("TOK: typ=%s %d-%d\n", lexer_token_type_name(lex->tok_type), lex->tok_start, lex->tok_end);
        }
    }
}
