[package]
name = "zowski"
version = "0.1.0"
authors = ["Windel Bouwman <windel@windel.nl>"]
edition = "2018"

[dependencies]

serde = { version = "1", features = ["derive"] }
tera = { version = "1", default-features = false }
