/*
Demo of C code generated by the scanner generator.

*/
#include <stdio.h>
#include <string.h>

#include "scanner.h"

void main() {
    char* test_text = "67432 2323.3  bla    9032.356789823  ++ mo";

    zowski_lexer_t* lex = zowski_lexer_new();

    printf("Scanning: %s (len=%d)\n", test_text, strlen(test_text));

    #define TOKEN_TEXT_BUFSIZE 30
    char buf[TOKEN_TEXT_BUFSIZE];
    zowski_result_t res;

    zowski_lexer_feed(lex, test_text, strlen(test_text));

    do {
        res = zowski_lexer_next_token(lex);
        switch (res) {
            case ZOWSKI_RESULT_OK:
                {
                    // display token:
                    zowski_lexer_token_copy_text(lex, buf, TOKEN_TEXT_BUFSIZE);
                    int tok_start = zowski_lexer_get_token_start(lex);
                    int tok_end = zowski_lexer_get_token_end(lex);
                    const char* tok_name = zowski_lexer_token_type_name(lex);

                    printf("TOK: typ=%s %d-%d: [%s]\n", tok_name, tok_start, tok_end, buf);
                }
                break;
            case ZOWSKI_RESULT_ERROR:
                printf("Errorzz!\n");
                break;
            case ZOWSKI_RESULT_FINISHED:
                break;
            default:
                printf("Now what?\n");
                break;
        }
    } while (res == ZOWSKI_RESULT_OK);

    zowski_lexer_delete(lex);
}
