/*
Demo of C code generated by the scanner generator.

*/
#include <stdio.h>
#include <string.h>

#include "scanner.h"

void main() {
    char* test_text = "67432 2323.3  bla +++  mo";

    lexer_t* lex = lexer_new();

    printf("Scanning: %s (len=%d)\n", test_text, strlen(test_text));

    while (test_text[lex->index] != 0) {
        int c = test_text[lex->index++];
        lexer_add(lex, c);
        if (lex->state == 0)
        {
            if (lex->tok_type == TOKEN_ERROR)
            {
                
            }
            else
            {
                lex->index = lex->tok_end;
                printf("TOK: typ=%s %d-%d\n", lexer_token_type_name(lex->tok_type), lex->tok_start, lex->tok_end);
            }
        }
    }
}
